/**
 * Never Have I Ever
 * @description Get a random Never Have I Ever statement sent back after function has been ran.
 * @nsfw This function does not contain Not-Safe-For-Work content.
 * @updated Fri May 5, 2023
 */

export const NHIE = () => {
  var nhies = [
    'Never have I ever applied for Partner on Discord.',
    'Never have I ever applied for HypeSquad on Discord.',
    'Never have I ever been kicked/muted/banned from a server for breaking the rules.',
    'Never have I ever bought Nitro.',
    'Never have I ever got over 20 pings from Discord in 24 hours.',
    'Never have I ever pinged "@here" or "@everyone" in a server with 100+ people.',
    'Never have I ever made a bot on Discord.',
    'Never have I ever had an OG discriminator such as #0001.',
    'Never have I ever dated on Discord.',
    'Never have I ever been staff on a server with 100+ people.',
    'Never have I ever experienced a raid on Discord.',
    'Never have I ever [blurplefied](https://www.urbandictionary.com/define.php?term=Blurplefy) my profile picture or server icon.',
    'Never have I ever liked the light theme of Discord.',
    'Never have I ever used /tts to annoy people.',
    'Never have I ever farted in front of someone I liked.',
    'Never have I ever accidentally sharted.',
    'Never have I ever forgotten the punchline of a joke.',
    'Never have I ever sang a song out loud and messed the lyrics.',
    'Never have I ever walked in on someone in the bathroom.',
    'Never have I ever had someone walk in on me in the bathroom.',
    'Never have I ever sent a text to the wrong person.',
    'Never have I ever tried to pass a silent fart, but it came out loud instead.',
    'Never have I ever tripped in public.',
    'Never have I ever wet the bed after childhood.',
    'Never have I ever accidentally pooped my pants.',
    'Never have I ever attempted martial arts moves while by myself.',
    'Never have I ever drove over a curb.',
    'Never have I ever mistaken a man for a women or vice versa.',
    'Never have I ever laughed so hard, I peed my pants.',
    'Never have I ever picked a wedgie in public.',
    'Never have I ever called the wrong person, but pretended I meant to call them.',
    'Never have I ever gone into the wrong restroom.',
    'Never have I ever been so freaked to be outside at night, that I ran back in.',
    'Never have I ever lost my swimwear bottoms.',
    "Never have I ever had diarrhea at a friend's house.",
    'Never have I ever broken a piece of furniture by sitting on it.',
    'Never have I ever arrived somewhere late and had everyone staring at me.',
    'Never have I ever had food stuck in my teeth all day',
    'Never have I ever walked around with my zipper down.',
    "Never have I ever bought a children's toy for myself.",
    'Never have I ever recorded video of myself singing or dancing.',
    'Never have I ever been caught picking my nose.',
    'Never have I ever gotten something stuck in my nose.',
    'Never have I ever greeted someone I thought was someone else.',
    'Never have I ever gave myself a bad haircut.',
    'Never have I ever been told I had bad breath.',
    'Never have I ever screamed because of a bug.',
    "Never have I ever played on my phone, trying to look like I'm doing something important.",
    'Never have I ever practiced public speaking in the mirror.',
    'Never have I ever had dandruff.',
    'Never have I ever listened to Justin Bieber.',
    'Never have I ever just looked at myself naked in the mirror.',
    'Never have I ever pretended to wash my hands by turning the water on, just in case someone is listening.',
    "Never have I ever smiled at someone when I realize I wasn't listening to what they were saying.",
    'Never have I ever tried to impress a crush by seeming knowledgeable about things they liked.',
    'Never have I ever refreshed over and over to see if I have any new messages.',
    'Never have I ever pretended to text while you secretly take a million selfies.',
    'Never have I ever been obsessed with One Direction.',
    'Never have I ever imagined my life as a sitcom and who would play me.',
    'Never have I ever binge-eaten Little Debbie cakes.',
    'Never have I ever eaten at Taco Bell more than 3 times in a week.',
    'Never have I ever eaten a carton of ice cream by myself.',
    "Never have I ever been to Arby's.",
    'Never have I ever had a deep fried candy bar.',
    "Never have I ever eaten from someone else's plate when they weren't looking.",
    'Never have I ever eaten something cold because I was too lazy to heat it up.',
    'Never have I ever eaten pumpkin pie.',
    'Never have I ever tried chicken and waffles.',
    'Never have I ever tried anchovies.',
    'Never have I ever dipped french fries into a milkshake.',
    'Never have I ever eaten a salad.',
    'Never have I ever bought myself a Happy Meal.',
    'Never have I ever eaten more than 3 hot dogs at once.',
    "Never have I ever tried a restaurant's food challenge.",
    'Never have I ever tried to eat 6 saltines in a minute.',
    'Never have I ever put ice cubes in my milk and cereal.',
    'Never have I ever drank pickle juice.',
    'Never have I ever put candy on pizza.',
    'Never have I ever tried pickles with peanut butter.',
    'Never have I ever salted watermelon.',
    'Never have I ever tried a banana and mayonnaise sandwich.',
    'Never have I ever tried baby food.',
    'Never have I ever eaten a full frozen pizza by myself.',
    'Never have I ever made a gross smoothie.',
    'Never have I ever tried counting how many licks it took to get to the center of a Tootsie Pop.',
    'Never have I ever drank Surge.',
    'Never have I ever eaten pop rocks.',
    'Never have I ever had a hot pocket.',
    'Never have I ever eaten alligator.',
    'Never have I ever tried bbq pork nachos.',
    'Never have I ever cleaned out the fridge and found food over a year old.',
    'Never have I ever cooked Thanksgiving dinner.',
    'Never have I ever counted calories.',
    'Never have I ever burnt my mouth willingly because I was too hungry to wait.',
    'Never have I ever eaten Spam.',
    'Never have I ever chewed with my mouth open.',
    'Never have I ever used a baby spoon to eat ice cream so it would last longer.',
    'Never have I ever eaten butter by itself.',
    'Never have I ever eaten food while still standing with the fridge door open.',
    'Never have I ever eaten a spoon full of frosting.',
    'Never have I ever tried Taco Bell breakfast.',
    'Never have I ever daydreamed about donuts.',
    'Never have I ever eaten pizza for two or more meals in a day.',
    'Never have I ever tried eggs with runny yolks.',
    'Never have I ever eaten the whole pizza by myself',
    'Never have I ever tried to drink a complete glass of cola in one go',
    'Never have I ever binge eaten while angry or upset',
    'Never have I ever I have eaten a litre of icecream bucket in one go.',
    'Never have I ever eaten pork.',
    'Never have I ever eaten an exotic fruit. (passion fruit, mango etc.)',
    'Never have I ever drunk coconut milk.',
    'Never have I ever watched the Ghostbusters remake.',
    'Never have I ever wanted to be one of the Kardashians.',
    'Never have I ever dressed as the opposite sex.',
    'Never have I ever watched "Spongebob Squarepants".',
    'Never have I ever cried during a Pixar movie. (Darn you Bing Bong!)',
    'Never have I ever had a crush, or man crush, on Ron Swanson.',
    "Never have I ever 'cleaned up' by piling everything into a closet.",
    'Never have I ever sung karaoke.',
    'Never have I ever watched the Gangnam Style music video.',
    'Never have I ever had a crush on someone from "Full House".',
    'Never have I ever watched an episode of "Gilmore Girls".',
    'Never have I ever pretended to know a stranger.',
    'Never have I ever worn sleepwear and pretended it was clothing.',
    "Never have I ever said 'excuse me' when there was no one around.",
    'Never have I ever scared myself in a mirror.',
    'Never have I ever missed a high five.',
    'Never have I ever heard someone else doing it.',
    'Never have I ever sang in the shower.',
    'Never have I ever blamed farts on an animal.',
    'Never have I ever secretly wished I were a wizard at Hogwarts.',
    'Never have I ever slept in regular clothing.',
    'Never have I ever had a nightmare about zombies chasing me.',
    "Never have I ever pretended to laugh at a joke I didn't get.",
    'Never have I ever been scared of clowns.',
    'Never have I ever thought a cartoon character was hot.',
    'Never have I ever faked being sick so I could play video games.',
    'Never have I ever liked Star Wars more than Star Trek.',
    'Never have I ever tried out to be an extra in a movie.',
    'Never have I ever scored over 100 while bowling.',
    'Never have I ever used an Instant Pot.',
    'Never have I ever played Candy Crush.',
    'Never have I ever won a game of Scrabble.',
    'Never have I ever made a duck face when taking a selfie.',
    "Never have I ever looked out the car's passenger seat window and imagined it was a scene from a music video.",
    'Never have I ever actually laughed out loud when typing LOL.',
    'Never have I ever reread an email immediately after sending it.',
    "Never have I ever daydreamed about being on a talk show and what I'd talk about.",
    'Never have I ever Googled my own name to see what comes up.',
    'Never have I ever pretended I was running from zombies while on a run.',
    'Never have I ever sat in the shower.',
    'Never have I ever tried something I saw on Pinterest.',
    'Never have I ever ugly cried for no reason.',
    'Never have I ever creeped on someone I just met on social media.',
    'Never have I ever thought about how a loved one could identify me if my face was horribly disfigured in an accident.',
    "Never have I ever answered someone 'left' or 'right' without thinking, because I have a 50/50 chance of being right.",
    'Never have I ever ran out of the class while it was in progress',
    'Never have I ever peed in the swimming pool',
    'Never have I ever thrown up in public.',
    'Never have I ever being caught while picking up my nose',
    'Never have I ever pretend to be bathing',
    'Never have I ever worn the same underwear twice',
    "Never have I ever stuck a gum on someone's hair",
    'Never have I ever played Minecraft.',
    'Never have I ever played Fortnite.',
    'Never have I ever googled "free vbucks on fortnite".',
    'Never have I ever cheated on my wife in Sims.',
    'Never have I ever spent over $100 on a game or game items.',
    'Never have I ever played CS:GO.',
    'Never have I ever played a game over 3,000 hours.',
    'Never have I ever sat on a public toilet.',
    'Never have I ever put gum under a table.',
    'Never have I ever stepped barefoot in dog poop.',
    'Never have I ever tasted dog or cat food.',
    'Never have I ever had a baby spit up on me.',
    'Never have I ever thrown up after seeing someone else throw up.',
    'Never have I ever picked my nose and ate it.',
    "Never have I ever used someone else's toothbrush.",
    "Never have I ever worn someone else's underwear.",
    'Never have I ever used my hands as a tissue (out of necessity).',
    'Never have I ever crop dusted an elevator.',
    'Never have I ever peed in the pool.',
    'Never have I ever clogged a toilet.',
    'Never have I ever tasted earwax.',
    'Never have I ever wiped my armpits with a towel instead of showering.',
    'Never have I ever worn the same pair of underwear more than 3 days.',
    'Never have I ever destroyed a public bathroom.',
    'Never have I ever thrown up in my mouth and swallowed it.',
    'Never have I ever used a public restroom that had no toilet paper.',
    "Never have I ever wore perfume or cologne because I didn't have deodorant.",
    "Never have I ever broken the '5-second rule'.",
    'Never have I ever gotten poop on my hand.',
    "Never have I ever had such bad diarrhea that I didn't make it to the bathroom in time.",
    'Never have I ever thought a fart smelled good.',
    'Never have I ever licked a coin.',
    'Never have I ever worn the same jeans for a week without washing them.',
    'Never have I ever changed a diaper.',
    'Never have I ever gone more than a week without showering.',
    'Never have I ever had a smelly burp.',
    'Never have I ever watched pimple popping videos.',
    'Never have I ever peeled a sunburn and enjoyed it.',
    'Never have I ever picked a scab.',
    'Never have I ever picked stuff out of my belly button.',
    'Never have I ever used the bathroom and not washed my hands.',
    'Never have I ever smelled clothing to see if they were too dirty to wear again.',
    'Never have I ever had stinky feet.',
    'Never have I ever let dirty dishes sit in the sink for over a week.',
    'Never have I ever blown my nose and looked at what came out.',
    'Never have I ever trimmed my toenails with my teeth.',
    'Never have I ever turned underwear inside out to get more use out of it.',
    "Never have I ever popped someone else's pimple.",
    'Never have I ever peeling dead skin off my feet.',
    'Never have I ever rubbed my skin to get the dead skin to roll up.',
    'Never have I ever peed in the sink.',
    'Never have I ever had a drop land on the toilet seat and not cleaned it off.',
    'Never have I ever been to Disney World.',
    'Never have I ever played Mario',
    'Never have I ever shot a gun',
    'Never have I ever crashed a car',
    'Never have I ever travelled with a stranger',
    'Never have I ever forged the signature of my parents on report card',
    'Never have I ever failed a class.',
    'Never have I ever stayed up for more than 24 hours',
    'Never have I ever lost the keys of my house',
    'Never have I ever ridden an animal',
    'Never have I ever convinced someone to get the tattoo similar to mine',
    'Never have I tried to cut my own hair',
    'Never have I stood dumb during a play',
    'Never have I ever taken a lift from a stranger',
    'Never have I jumped out of a moving train',
    'Never have I ever had the experience of being close to death',
    'Never have I re-gifted something that was gifted to me',
    'Never have I ever been out of the country.',
    'Never have I ever regifted a gift card.',
    'Never have I ever traveled out of state by myself.',
    'Never have I ever flown in a helicopter.',
    'Never have I ever been on stage in front of a crowd.',
    'Never have I ever lied in a job interview.',
    'Never have I ever stalked a crush.',
    'Never have I ever sung karaoke.',
    'Never have I ever agreed with something Donald Trump said.',
    'Never have I ever thought about what type of dog I would be.',
    "Never have I ever watched children's cartoons I'm too old for.",
    'Never have I ever lost sunglasses that I was already wearing.',
    'Never have I ever locked my keys in my car.',
    'Never have I ever not tipped at a restaurant.',
    'Never have I ever given money to a homeless person.',
    'Never have I ever tried to look at the sun.',
    'Never have I ever bungee-jumped.',
    'Never have I ever had surgery.',
    'Never have I ever jumped out of a plane.',
    'Never have I ever made a wish at a fountain.',
    'Never have I ever accidentally eaten a bug.',
    'Never have I ever cut someone in line.',
    'Never have I ever stayed up all night.',
    'Never have I ever read a single Harry Potter book.',
    'Never have I ever been inside of a library.',
    'Never have I ever lied about my age.',
    'Never have I ever shot a gun.',
    'Never have I ever had a cavity.',
    'Never have I ever been mini golfing.',
    'Never have I ever seen an elephant in real life.',
    'Never have I ever been to Disney World.',
    'Never have I ever bought clothing online.',
    'Never have I ever had someone draw a caricature of me.',
    'Never have I ever owned an Xbox.',
    'Never have I ever spent hours watching funny videos on Youtube.',
    'Never have I ever seen Titanic.',
    'Never have I ever met a celebrity.',
    'Never have I ever thought a movie was better than the book.',
    'Never have I ever voted.',
    'Never have I ever owned a watch.',
    'Never have I ever ridden a skateboard.',
    'Never have I ever learned how to play a musical instrument.',
    'Never have I ever seen snow.',
    'Never have I ever finished a Sudoku puzzle.',
    "Never have I ever Googled something so I'd know how to spell it.",
    'Never have I ever laughed so hard that I peed in my pants',
    'Never have I ever faked fever to miss school',
    "Never have I ever secretly eaten my baby's baby food",
    'Never have I ever thought of being a student of Hogwarts',
    'Never have I ever had a crush on my teacher',
    'Never have I ever sang a song and the background music had stopped',
    "Never have I ever stolen money from my father's wallet",
    'Never have I ever wanted to be reborn as a dog',
    'Never have I ever wished to be a superhero',
    'Never have I ever cried in public',
    'Never have I ever made dumb faces looking in the mirror',
    'Never have I ever cried watching a movie',
    'Never have I tried to repeat an action scene in the house',
    "Never have I wanted to read my spouse's mind while he/she said I Love You",
    'Never have I ever travelled alone',
    'Never have I ever counted the number of electric poles from a moving train',
    'Never have I wished something from a metriote.',
    'Never have I ever been pulled over.',
    'Never have I ever tried to flee the cops.',
    'Never have I ever driven drunk.',
    'Never have I ever been arrested.',
    'Never have I ever used a fake I.D.',
    'Never have I ever snuck into a club.',
    'Never have I ever smuggled food or candy into a movie theater.',
    'Never have I ever stolen money from someone.',
    'Never have I ever been in handcuffs.',
    'Never have I ever spent time in detention.',
    'Never have I ever snuck out of the house.',
    'Never have I ever lied to my parents about where I was going.',
    'Never have I ever crashed a party or wedding.',
    'Never have I ever shoplifted from a store.',
    'Never have I ever had to call the cops on someone.',
    'Never have I ever gotten into a fistfight.',
    'Never have I ever dated someone who was underage.',
    'Never have I ever thrown something at a moving car.',
    'Never have I ever called the cops on someone.',
    'Never have I ever flirted with a police officer in hopes of not getting a ticket.',
    'Never have I ever lied to a police officer.',
    'Never have I ever prank called 911. (Bad idea!)',
    'Never have I ever bought something stolen.',
    'Never have I ever dine and dashed.',
    'Never have I ever been drunk in public.',
    'Never have I ever littered.',
    'Never have I ever ran a red light.',
    'Never have I ever broken in somewhere.',
    'Never have I ever jumped a fence.',
    'Never have I ever been drinking before I was 21.',
    'Never have I ever returned an item I used or clothing I wore.',
    'Never have I ever downloaded music illegally.',
    'Never have I ever used wifi from an unsecured network.',
    'Never have I ever spit out gum onto the ground.',
    'Never have I ever jaywalked.',
    "Never have I ever shared passwords to services so family or friends didn't have to pay.",
    'Never have I ever been in violation of a school dress code.',
    'Never have I ever made a fake social media account.',
    'Never have I ever played poker at home for money.',
    'Never have I ever driven without wearing a seatbelt.',
    'Never have I ever used my cell phone while driving.',
    'Never have I ever crossed state lines to buy better fireworks.',
    'Never have I ever used medicine that was prescribed to me.',
    'Never have I ever ridden a bike on the sidewalk.',
    "Never have I ever passed a vehicle in a 'no passing' zone.",
    'Never have I ever broken the traffic signal',
    'Never have I ever travelled without ticket',
    'Never have I ever done drink and drive',
    'Never I have ever been handcuffed',
    'Never have I ever shoplifted something.',
    'Never have I ever lied to my parents about where I was going.',
    'Never have I ever indulged in a fight during a party',
  ];
  var nhie = nhies[Math.floor(Math.random() * nhies.length)];
  return nhie;
};
